# =============================================================================
# ATLAZES OS - Calamares Bootloader Module
# =============================================================================

---
# Install GRUB
efiBootLoader: "grub"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

# GRUB timeout
grubTimeout: 5

# Write os-prober
writeOsprober: true

# GRUB install options
grubInstallArguments:
    - "--target=x86_64-efi"
    - "--efi-directory=/boot/efi"
    - "--bootloader-id=ATLAZES"
    - "--recheck"

# BIOS fallback
grubBiosInstallArguments:
    - "--target=i386-pc"
    - "--recheck"
