---
backend: apt

operations:
    - remove:
        - calamares
        - calamares-settings-debian
        - live-boot
        - live-boot-initramfs-tools
        - live-config
        - live-config-systemd
        - live-tools
        - open-vm-tools
        - open-vm-tools-desktop
    - install:
        - linux-image-amd64
        - grub-efi-amd64
