# =============================================================================
# ATLAZES OS - Calamares Unpackfs Module
# =============================================================================

---
unpack:
    -   source: "/run/live/medium/live/filesystem.squashfs"
        sourcefs: "squashfs"
        destination: ""
