---
defaultGroups:
    - name: sudo
      state: true
    - name: audio
      state: true
    - name: video
      state: true
    - name: plugdev
      state: true
    - name: netdev
      state: true
    - name: bluetooth
      state: true

autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: true
doReusePassword: false
passwordRequirements:
    minLength: 6
    maxLength: -1
    libpwquality:
        - minlen=6

userShell: /bin/bash
