# =============================================================================
# ATLAZES OS - Calamares Welcome Module
# =============================================================================

---
# Show "What's new" button
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false

# Requirements check
requirements:
    checker:
        - storage:
            required: 20
            recommended: 40
        - ram:
            required: 1024
            recommended: 4096
        - power:
            required: false
        - internet:
            required: false
        - root:
            required: true
        - screen:
            required: false

# Geoip for locale detection
geoip:
    style: "json"
    url: "https://geoip.kde.org/v1/calamares"
